wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1648354605
    t:
      3:
      - 2
      - 13
      - 16
      4: 3.9.5
      5: 0.12.11
      8:
      - 1
      - 3
      - 5
