wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1648343400
    t:
      3:
      - 13
      - 16
      4: 3.9.5
      5: 0.12.11
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: Genetic Algorithm
collision_penalty:
  desc: null
  value: 400
config_file:
  desc: null
  value: Manhattan5x3.sumocfg
crossover_rate:
  desc: null
  value: 0.5
duration_mutation_rate:
  desc: null
  value: 0.2
duration_mutation_strength:
  desc: null
  value: 5
emissions_weight:
  desc: null
  value: 0.0005
max_generations:
  desc: null
  value: 100
n_survivors:
  desc: null
  value: 3
population_size:
  desc: null
  value: 15
states_mutation_rate:
  desc: null
  value: 0.2
waiting_time_weight:
  desc: null
  value: 0.0005
